### ISSUE TITLE
Class 'Faker\Factory' not found

### ISSUE THREAD

**Issue by Manoz** [dewsign/nova-tool-redirects#4]
Hey,

Nice work for your package :)

I have a weird issue when using it tho.
If I simply `composer install` with your package in my `composer.json` file, everything looks ok and it works perfectly.

When I try to deploy my application on production env, I'm using `composer install --no-dev` obviously and I have an issue saying: 

```
In DatabaseServiceProvider.php line 78:
                                   
  Class 'Faker\Factory' not found  
                                   

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

Obviously Faker is used in our dev dependencies so that's why I have this issue.

Here's some more logs I've found:

```
#9 vendor/dewsign/nova-tool-redirects/src-php/Providers/PackageServiceProvider.php(90): Illuminate\\Foundation\\Application->make('Illuminate\\\\Data...')
#10 vendor/dewsign/nova-tool-redirects/src-php/Providers/PackageServiceProvider.php(23): Dewsign\\NovaToolRedirects\\Providers\\PackageServiceProvider->publishDatabaseFiles()
#11 [internal function]: Dewsign\\NovaToolRedirects\\Providers\\PackageServiceProvider->boot(Object(Illuminate\\Routing\\Router))
```

Thank you in advance

**Comment by PopMishima** [comment]
you need only just `composer install` without the --no-dev option. Faker is supposedly for development, hence it's included under the required-dev section of composer.json, not production-ready required section.

**Comment by m2de** [comment]
This has been resolved, just forgot to close the issue. Thanks though @PopMishima .

**Comment by Manoz** [comment]
Lol yes sorry. Don't even remember why I've created this issue ^_^
